"use client";

import { useRef, useState } from "react";
import Image from "next/image";
import Link from "next/link";
import { ArrowDown, ArrowRight, ArrowUpRight, BookOpen, Bookmark, Compass, Feather, MapPin, Search, Sparkles } from "lucide-react";
import { useReducedMotion } from "framer-motion";
import { formatStoryDate, publishedStories, researchDate, storyCategories } from "@/data/researchedTravelStories";
import { StoryArtwork, StoryReveal, storyButton, storyHeading, storyShell, useSavedStories } from "./StoryShared";
import StoryDraft from "./StoryDraft";

export default function TravelStoriesPage() {
  const reduced = useReducedMotion();
  const [category, setCategory] = useState<string>("All stories");
  const [query, setQuery] = useState("");
  const [savedOnly, setSavedOnly] = useState(false);
  const [sort, setSort] = useState("curated");
  const { saved, toggle, warning } = useSavedStories();
  const feed = useRef<HTMLElement>(null);
  const featured = publishedStories[0];
  const filtered = publishedStories.filter(story => (category === "All stories" || story.category === category)
    && (!savedOnly || saved.includes(story.slug))
    && `${story.title} ${story.destination} ${story.author ?? ""} ${story.publisher} ${story.excerpt}`.toLowerCase().includes(query.trim().toLowerCase()));
  const visible = sort === "newest" ? [...filtered].sort((a, b) => b.published.localeCompare(a.published)) : filtered;
  const browse = () => feed.current?.scrollIntoView({ behavior: reduced ? "auto" : "smooth", block: "start" });

  return <div className="overflow-x-clip bg-[#F7F7F2] text-[#17211D] selection:bg-[#F4B942]/30">
    <section className="relative isolate overflow-hidden rounded-b-[28px] bg-[#071A16]">
      <Image src="/assets/Sajek/cover-3.jpg" alt="Bangladesh hill landscape from the project image collection" fill priority sizes="100vw" className="-z-20 object-cover" />
      <div className="absolute inset-0 -z-10 bg-gradient-to-r from-[#031D16]/95 via-[#071A16]/80 to-[#071A16]/40" />
      <div className={`${storyShell} grid items-center gap-10 pb-16 pt-36 sm:pb-20 sm:pt-40 lg:grid-cols-[1.15fr_0.85fr] lg:pb-24 lg:pt-44`}>
        <StoryReveal>
          <div className="mb-6 flex items-center gap-3 text-[10px] font-semibold uppercase tracking-[0.22em] text-[#D4DDD4]"><span className="h-px w-8 bg-[#F4B942]" /> Inspiration / Travel stories</div>
          <h1 className="max-w-2xl font-serif text-[46px] leading-[1.02] tracking-[-0.045em] text-white sm:text-[65px] lg:text-[78px]">Every journey<br />leaves a <span className="italic text-[#FFD078]">story.</span></h1>
          <p className="mt-6 max-w-md text-sm leading-7 text-white/75 sm:text-base">The people we meet. The paths we didn’t plan.<br className="hidden sm:block" /> Discover Bangladesh through published journeys and the moments that stayed.</p>
          <div className="mt-8 flex flex-wrap gap-3"><button onClick={browse} className={storyButton}>Explore stories <ArrowDown size={16} /></button><StoryDraft compact /></div>
          <p className="mt-7 flex items-center gap-2 text-[11px] text-white/60"><BookOpen size={14} /> Original authors credited · Sources linked</p>
        </StoryReveal>
        <StoryReveal className="hidden lg:block" delay={0.12}>
          <Link href={`/inspiration/stories/${featured.slug}`} className="group relative mx-auto block max-w-[370px] rotate-3 rounded-[3px] bg-[#FFFCF4] p-3 pb-5 shadow-2xl transition-transform duration-500 motion-safe:hover:rotate-0">
            <div className="relative h-64 overflow-hidden"><StoryArtwork story={featured} /><span className="absolute bottom-3 left-3 rounded-full bg-white/90 px-3 py-1.5 text-[10px] text-[#204B3D]">Jaflong · Destination image</span></div>
            <div className="px-3 pt-5"><p className="text-[9px] font-semibold uppercase tracking-[0.2em] text-[#839181]">A page from Bangladesh</p><p className="mt-2 font-serif text-[26px] leading-tight">More than a place.<br /><span className="italic text-[#087F5B]">A new perspective.</span></p><span className="mt-4 flex items-center justify-between text-[11px] text-[#63786C]">Discover the featured story <ArrowUpRight size={17} /></span></div>
          </Link>
        </StoryReveal>
      </div>
    </section>

    <nav aria-label="Inspiration pages" className="border-b border-[#DCE5DA] bg-[#F7F7F2]"><div className={`${storyShell} flex items-center justify-between gap-4 overflow-x-auto py-4 text-xs`}><div className="flex shrink-0 gap-6"><Link href="/inspiration/guides" className="text-[#67796B] hover:text-[#087F5B]">Travel Guides</Link><span className="font-semibold text-[#087F5B]" aria-current="page">Travel Stories</span></div><a href="#story-sources" className="shrink-0 text-[#67796B] hover:text-[#087F5B]">Meet the sources <ArrowUpRight size={13} className="ml-1 inline" /></a></div></nav>

    <section aria-labelledby="featured-story" className={`${storyShell} py-12 sm:py-16`}>
      <StoryReveal><p className="mb-5 flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.2em] text-[#087F5B]"><Feather size={14} /> The featured journey</p>
        <div className="grid overflow-hidden rounded-[24px] border border-[#DDE5DB] bg-[#FFFEF9] lg:grid-cols-[1.1fr_1fr]">
          <Link aria-label={`Read ${featured.title}`} href={`/inspiration/stories/${featured.slug}`} className="group relative block min-h-[280px] overflow-hidden sm:min-h-[360px]"><StoryArtwork story={featured} /><span className="absolute bottom-5 left-5 flex items-center gap-1 rounded-full bg-white/90 px-3 py-1.5 text-[11px] text-[#204B3D]"><MapPin size={12} /> {featured.destination}</span></Link>
          <div className="flex flex-col justify-center p-6 sm:p-9 lg:p-11"><p className="text-[10px] font-semibold uppercase tracking-wider text-[#A5762A]">{featured.category} · Published account</p><h2 id="featured-story" className={`${storyHeading} mt-4`}><Link href={`/inspiration/stories/${featured.slug}`} className="hover:text-[#087F5B]">{featured.title}</Link></h2><p className="mt-4 text-sm leading-7 text-[#68776D]">{featured.excerpt}</p><div className="mt-6 flex items-center gap-3"><span aria-hidden="true" className="flex h-10 w-10 items-center justify-center rounded-full bg-[#EAF0E6] font-serif text-sm text-[#087F5B]">EE</span><div><p className="text-xs font-semibold">{featured.author}</p><p className="mt-1 text-[10px] text-[#758477]">{featured.publisher} · {formatStoryDate(featured.published)}</p></div></div><Link href={`/inspiration/stories/${featured.slug}`} className="mt-7 inline-flex items-center gap-3 self-start border-b border-[#087F5B]/25 pb-1 text-sm font-semibold text-[#087F5B]">Read the summary <ArrowRight size={17} /></Link></div>
        </div>
      </StoryReveal>
    </section>

    <section ref={feed} id="stories" aria-labelledby="stories-title" className={`${storyShell} scroll-mt-28 pb-14 sm:pb-20`}>
      <StoryReveal><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="mb-3 text-[10px] font-semibold uppercase tracking-[0.18em] text-[#087F5B]">The reading room</p><h2 id="stories-title" className={storyHeading}>Find a story that stays with you.</h2><p className="mt-3 text-sm text-[#6E7C70]">Short editorial summaries. Real published perspectives.</p></div><button onClick={() => setSavedOnly(!savedOnly)} aria-pressed={savedOnly} className={`flex items-center gap-2 rounded-full border px-4 py-2.5 text-xs ${savedOnly ? "border-[#087F5B] bg-[#087F5B] text-white" : "border-[#D2DFD4] text-[#365646] hover:bg-white"}`}><Bookmark size={14} fill={savedOnly ? "currentColor" : "none"} /> My reading list ({saved.length})</button></div>
      <div className="mt-7 flex flex-col gap-4 border-y border-[#DCE5DA] py-4 xl:flex-row xl:items-center xl:justify-between"><div className="flex flex-wrap gap-2">{storyCategories.map(item => <button key={item} aria-pressed={category === item} onClick={() => setCategory(item)} className={`rounded-full px-4 py-2 text-xs transition ${category === item ? "bg-[#087F5B] text-white" : "text-[#627868] hover:bg-[#E9EFE6]"}`}>{item}</button>)}</div><div className="flex flex-wrap items-center gap-3"><label className="flex min-w-0 flex-1 items-center gap-2 rounded-full border border-[#D4DFD3] bg-white/70 px-3 py-2"><Search size={15} className="shrink-0 text-[#788A79]" /><span className="sr-only">Search stories</span><input type="search" placeholder="Find a place or story" value={query} onChange={event => setQuery(event.target.value)} className="w-full min-w-0 bg-transparent text-xs outline-none sm:w-40" /></label><label className="text-xs text-[#627868]"><span className="sr-only">Sort stories</span><select value={sort} onChange={event => setSort(event.target.value)} className="rounded-lg bg-transparent py-2 outline-offset-2"><option value="curated">Editor’s order</option><option value="newest">Newest published</option></select></label></div></div></StoryReveal>
      <p aria-live="polite" className="my-5 text-[11px] text-[#7A887B]">{visible.length} {visible.length === 1 ? "story" : "stories"}{savedOnly ? " in your reading list" : " to discover"}</p>
      <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{visible.map((story, index) => <StoryReveal key={story.slug} delay={(index % 3) * 0.05}><article className="group flex h-full flex-col overflow-hidden rounded-[20px] border border-[#DCE5DA] bg-[#FFFEF9] transition duration-300 hover:shadow-[0_14px_40px_rgba(7,61,49,0.08)] motion-safe:hover:-translate-y-1"><Link href={`/inspiration/stories/${story.slug}`} aria-label={`Read ${story.title}`} className="relative block aspect-[1.55] overflow-hidden"><StoryArtwork story={story} /><span className="absolute left-4 top-4 rounded-full bg-[#FFFEF9]/90 px-3 py-1.5 text-[10px] font-medium text-[#345442]">{story.category}</span><span className="absolute bottom-3 right-3 rounded-md bg-[#073D31]/70 px-2 py-1 text-[8px] text-white">{story.image ? "Destination image" : "Illustration"}</span></Link><div className="flex flex-1 flex-col p-5 sm:p-6"><p className="flex items-center gap-1.5 text-[10px] text-[#8C794E]"><MapPin size={12} /> {story.destination}</p><h3 className="mt-3 font-serif text-[24px] leading-tight tracking-[-0.025em]"><Link href={`/inspiration/stories/${story.slug}`} className="hover:text-[#087F5B]">{story.title}</Link></h3><p className="mb-5 mt-3 text-xs leading-6 text-[#6B7B6F]">{story.excerpt}</p><div className="mt-auto flex items-end justify-between gap-3 border-t border-[#EBEDE4] pt-4"><div className="min-w-0"><p className="text-[11px] font-semibold">{story.author ?? story.publisher}</p><a href={story.sourceUrl} target="_blank" rel="noopener noreferrer" className="mt-1 inline-block text-[10px] text-[#788779] underline decoration-[#CDD7CA] underline-offset-2">{story.publisher} <ArrowUpRight size={10} className="inline" /></a><p className="mt-1 text-[10px] text-[#8B9589]">{formatStoryDate(story.published)}</p></div><button aria-label={`${saved.includes(story.slug) ? "Unsave" : "Save"} ${story.title}`} aria-pressed={saved.includes(story.slug)} onClick={() => toggle(story.slug)} className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full text-[#087F5B] transition hover:bg-[#E8F0E5]"><Bookmark size={18} fill={saved.includes(story.slug) ? "currentColor" : "none"} /></button></div></div></article></StoryReveal>)}</div>
      {!visible.length && <div className="rounded-2xl border border-dashed border-[#BFD0BF] px-5 py-14 text-center"><BookOpen size={28} className="mx-auto text-[#087F5B]" /><h3 className="mt-4 font-serif text-2xl">{savedOnly && !saved.length ? "A little space for your next good read." : "No stories match these filters."}</h3><p className="mt-3 text-sm text-[#6E7C70]">{savedOnly && !saved.length ? "Tap a bookmark to keep a story on this device." : "Try another destination, or reset your filters."}</p><button onClick={() => { setSavedOnly(false); setQuery(""); setCategory("All stories"); }} className="mt-5 text-sm font-semibold text-[#087F5B]">Explore all stories →</button></div>}
      {warning && <p role="status" className="mt-4 text-xs text-[#795B30]">{warning}</p>}
    </section>

    <section className="border-y border-[#DCE5DA] bg-[#EEF2E9] py-12 sm:py-16"><div className={storyShell}><StoryReveal><div className="mb-7 flex flex-wrap items-end justify-between gap-3"><div><p className="mb-3 text-[10px] font-semibold uppercase tracking-[0.18em] text-[#087F5B]">Small moments, lasting impressions</p><h2 className={storyHeading}>It’s often the people.</h2></div><p className="max-w-xs text-xs leading-6 text-[#788478]">Our reflections on three published journeys. Follow each story back to its original voice.</p></div><div className="grid gap-4 md:grid-cols-3">{[publishedStories[1], publishedStories[3], publishedStories[5]].map((story, i) => <Link key={story.slug} href={`/inspiration/stories/${story.slug}`} className="group flex flex-col rounded-2xl border border-[#D6E0D1] bg-[#F9FAF3] p-6 transition hover:bg-white"><span className="font-serif text-3xl italic text-[#A9BBA5]">0{i + 1}</span><p className="mb-6 mt-3 font-serif text-[23px] leading-snug text-[#284E3C]">{story.moment}</p><span className="mt-auto flex items-center justify-between text-[11px] text-[#6D806D]">{story.destination}<ArrowRight size={16} className="transition-transform motion-safe:group-hover:translate-x-1" /></span></Link>)}</div></StoryReveal></div></section>

    <section className={`${storyShell} py-14 sm:py-20`}><StoryReveal className="relative isolate overflow-hidden rounded-[26px] bg-[#073D31] px-6 py-10 sm:px-12 sm:py-14"><div className="pointer-events-none absolute -right-16 -top-24 -z-10 h-80 w-80 rounded-full border border-white/10" /><div className="pointer-events-none absolute -bottom-32 right-10 -z-10 h-80 w-80 rounded-full border border-white/10" /><div className="grid items-center gap-8 lg:grid-cols-[1.5fr_1fr]"><div><p className="text-[10px] uppercase tracking-[0.2em] text-[#BDD0B7]">The next page could be yours</p><h2 className="mt-4 font-serif text-3xl leading-tight tracking-tight text-white sm:text-[42px]">Your journey could inspire<br className="hidden sm:block" /> someone’s <span className="italic text-[#FFD078]">next.</span></h2><p className="mt-4 max-w-lg text-sm leading-7 text-white/65">An unexpected detour. A meal you still think about. A lesson worth passing on. Start with the moment that matters to you.</p></div><div className="lg:justify-self-end"><StoryDraft /><p className="mt-4 max-w-[220px] text-[11px] leading-5 text-white/55">Private drafts stay on your device.<br />Download a copy whenever you’re ready.</p></div></div></StoryReveal></section>

    <section id="story-sources" aria-labelledby="sources-heading" className={`${storyShell} scroll-mt-28 pb-14`}><details className="border-y border-[#D8E1D4] py-5"><summary className="cursor-pointer text-sm font-semibold text-[#335D43]"><span id="sources-heading">Sources & editorial notes</span><span className="ml-3 text-[10px] font-normal text-[#7D8C7A]">Checked {formatStoryDate(researchDate)}</span></summary><div className="pt-5 text-xs leading-6 text-[#687D69]"><p>These are TripPlan AI summaries of published writing, not reviews submitted by our users. Byline, publication and date refer to the original article. Story dates do not confirm present-day access, prices or safety. Scenic images are from the project collection; illustrations are decorative.</p><ol className="mt-5 grid gap-4 md:grid-cols-2">{publishedStories.map((story, i) => <li key={story.slug} className="rounded-xl bg-white/60 p-4"><p className="text-[#34523D]">{i + 1}. {story.author ?? "Personal byline not visible"} · {story.publisher}</p><a href={story.sourceUrl} target="_blank" rel="noopener noreferrer" className="underline underline-offset-4 hover:text-[#087F5B]">{story.sourceTitle} <ArrowUpRight size={11} className="inline" /></a><p>{formatStoryDate(story.published)}</p></li>)}</ol><p className="mt-5">The launch selection includes five pieces from The Business Standard and one from Dhaka Tribune. It is a curated starting point, not a representative survey of Bangladesh’s travelers. The Rajshahi account describes an organised tourism launch visit.</p></div></details></section>
    <section className={`${storyShell} pb-16 text-center`}><Compass size={24} strokeWidth={1.3} className="mx-auto mb-4 text-[#087F5B]" /><h2 className="font-serif text-2xl tracking-tight sm:text-3xl">Found a little inspiration?</h2><p className="mt-3 text-sm text-[#798575]">Give it a place in your next journey.</p><Link href="/plan-trip" className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-[#087F5B]"><Sparkles size={15} /> Plan My Trip <ArrowRight size={16} /></Link></section>
  </div>;
}
